### PR TITLE
rename tables

### PR DESCRIPTION
**Pull request by slodki**
After @vomikan @gabriele-v suggestion at moneymanagerex/moneymanagerex#709:

```sql
DROP TABLE IF EXISTS SPLITTRANSACTIONS_V2;
ALTER TABLE ACCOUNTLIST_V1 RENAME TO ACCOUNTLIST;
ALTER TABLE CUSTOMFIELDDATA_V1 RENAME TO CUSTOMFIELDDATA;
ALTER TABLE ASSETS_V1 RENAME TO ASSETS;
ALTER TABLE CUSTOMFIELD_V1 RENAME TO CUSTOMFIELD;
ALTER TABLE ATTACHMENT_V1 RENAME TO ATTACHMENT;
ALTER TABLE INFOTABLE_V1 RENAME TO INFOTABLE;
ALTER TABLE BILLSDEPOSITS_V1 RENAME TO BILLSDEPOSITS;
ALTER TABLE PAYEE_V1 RENAME TO PAYEE;
ALTER TABLE BUDGETSPLITTRANSACTIONS_V1 RENAME TO BUDGETSPLITTRANSACTIONS;
ALTER TABLE REPORT_V1 RENAME TO REPORT;
ALTER TABLE BUDGETTABLE_V1 RENAME TO BUDGETTABLE;
ALTER TABLE SHAREINFO_V1 RENAME TO SHAREINFO;
ALTER TABLE BUDGETYEAR_V1 RENAME TO BUDGETYEAR;
ALTER TABLE SPLITTRANSACTIONS_V1 RENAME TO SPLITTRANSACTIONS;
ALTER TABLE CATEGORY_V1 RENAME TO CATEGORY;
ALTER TABLE STOCKHISTORY_V1 RENAME TO STOCKHISTORY;
ALTER TABLE CHECKINGACCOUNT_V1 RENAME TO CHECKINGACCOUNT;
ALTER TABLE STOCK_V1 RENAME TO STOCK;
ALTER TABLE CURRENCYFORMATS_V1 RENAME TO CURRENCYFORMATS;
ALTER TABLE SUBCATEGORY_V1 RENAME TO SUBCATEGORY;
ALTER TABLE CURRENCYHISTORY_V1 RENAME TO CURRENCYHISTORY;
ALTER TABLE TRANSLINK_V1 RENAME TO TRANSLINK;
PRAGMA user_version = 11; 
```

### CODE REVIEW

**Comment by gabriele-v** [comment]
Few notes, considering that in the past MMEX suffered from poor DB Upgrades:
- I would create a V11 with creation of all tables and indexes (not only ATTACHMENT_V1 REPORT_V1 STOCKHISTORY_V1 CURRENCYHISTORY_V1) with IF NOT EXISTS clause
- We should find a way to check if all the fields are fine too (maybe V12?)
- After that, we are sure that all DB from here will be completely aligned
- Then in V13 we can rename all tables
- Add in V13 `DROP VIEW IF EXISTS alldata` (old view no more maintained)
- Add in V13 updates to fix reports
```
UPDATE REPORT SET SQLCONTENT = REPLACE(SQLCONTENT, '_V1', '' ) WHERE SQLCONTENT LIKE '%_V1%';
UPDATE REPORT SET LUACONTENT = REPLACE(LUACONTENT, '_V1', '' ) WHERE LUACONTENT LIKE '%_V1%';
UPDATE REPORT SET TEMPLATECONTENT = REPLACE(TEMPLATECONTENT, '_V1', '' ) WHERE TEMPLATECONTENT LIKE '%_V1%';
```
- Do you want to patch currencies too or we can keep mmdbg in case needed?
- Please keep everything in UPPER CASE, do not mix it with lower case


Obviously after that, a big search & replace in entire MMEX solution it's needed as well and we could consider to remove also `ensure(wxSQLite3Database* db) `and `ins.ensure(db);`, using tables.sql on new DB creation, to speedup MMEX startup a bit

**Comment by slodki** [comment]
ad. 1 - it's one time task, we have frozen v10 schema, so it's simple copy-paste change

ad. 2 - This is real problem - UNIQUE constraint was not added during upgrade... I don't know how to add single column only IF NOT EXIST in pure SQL or add UNIQUE/NOT NULL constraints...

ad. 3, 4 - maybe it's time for all tables rewrite like in v8->v9 upgrade script? CREATE TABLE IF NOT EXISTS OLD_V1, then CREATE TABLE NEW + INSERT INTO NEW FROM OLD_V1?

ad. 5 - I have found it...

ad. 6 - Someone should verify impact on GRM, usage data etc.

ad. 7 - we can remove unused currencies + add missing steps to upgrade procedure. We must not overwrite user settings for used currencies. We should keep separate script available as long as user can manually delete and change currencies IMHO.

ad. 8 - OK, I just copy+paste existing code...

Desktop MMEX code "search&replace" is ready and builds without errors...

**Comment by gabriele-v** [comment]
1. It was simply to divide patches in 2/3 steps, so if a user has a problem, it will easier to debug. In my idea we will need at least 3 different patches:
- 1. Ensure all table exists recreating all of the with IF NOT EXISTS
- 2. Ensure ilf all fields are fine
- 3. Rename tables removing _V1
- 4. Future updates like new SPLITTRANSDIALOG

2. What do you mean with unique not added? In which upgrade?
We could look at DB structure querying SQLITE_MASTER table
SELECT SQL FROM SQLITE_MASTER WHERE NAME='ACCOUNTLIST_V1';

3/4. I don't know how mouch could it take if you have a quite big DB, also in that case an optimize DB (VACUUM) from the menu it's mandatory because all data will be duplicated. But we could recreate just needed table using query above (to be tested if working)

6. What do you mean for impact? If we simply rename tables, then renaming also queries will fix GRM. Different if we will change structure, but for now it's not needed.

7. Ok, but keep in a different DB Version

Anyway I think that it's better to release quickly v 1.4.0 without this patches, becuase it already contains quite big changes in different areas, I'd prefer to avoid also problems on DB side.
Better to start releasing it, fix main bugs in 1.4.1 and after that we could think about 1.5.0 mainly focused on DB side.
I think it's better to keep MMEX main branch as is until 1.4.1, otherwise considering changes involved by table renaming we could have lots of conflicts problem merging fixes for 1.4.1 on 1.5.0 branch.

**Comment by slodki** [comment]
Problems with database and data already exist in 1.3.3/1.4.0 even if undetected/invisible. This cause errors when data is wrong or missing in current MMEX version. DB consistency can only help to fix such problems.

Simply renaming or dropping unused data cannot create new problems. Naming errors can be detect on compile time (C++) or statement compilation (SQL) and have clear error descriptions. This can be diagnosed and fixed really quickly.

Distributing new MMEX versions with known db problems will not help to fix bugs because overlaping problems with db and app code.

We don't have many branches to merge now, so this is good time for rename. After releasing 1.4.0 we will develop fixes in parallel and we will have many conflicts.

1.4.0 is minor version update and changes enforcing data consistency should be included. Changes like #23 can wait to 1.5.x.

**Comment by gabriele-v** [comment]
Ok, we can go for it in 1.4.0 but we need to decide how to proceed (recreate all tables or try to detect problems).
@moneymanagerex/desktop-mmex-team  what do you think?

**Comment by vomikan** [comment]
>gabriele-v added this to the v2.0 milestone about 1 hour ago

I am on the same point of view.

**Comment by slodki** [comment]
Rewritten to:
```sql
CREATE TABLE IF NOT EXISTS name_V1 (
column defs
...
);
CREATE TABLE name (
column defs
...
);
INSERT INTO name SELECT
columns
...
FROM name_V1;
DROP INDEX IF EXISTS idxname;
DROP TABLE name_V1;
CREATE INDEX idxname ON index def;
```

**Comment by gabriele-v** [comment]
Agree, for me it's ok, but could you re-base it after my PR? I need v11 to fix currency type.
Thanks

**Comment by slodki** [comment]
I cannot rebase my branch because your code is not available at this repo. Please push your changes as separate branch to moneymanagerex/database repo.

**Comment by gabriele-v** [comment]
No problem, I'll rebase mine that have less changes.

It's still missing a IF NOT EXISTS here:
https://github.com/moneymanagerex/database/blob/2e9f4f476c810c9bab0dd2cdc94faaa2b11e0637/database_version_9.sql#L3

**Comment by slodki** [comment]
fixed

**Comment by gabriele-v** [comment]
I'm merging it now but wait before merging in MMEX desktop so I'll add version 11 here.
Thanks

**Comment by gabriele-v** [comment]
Problem is that v11 has been made later than v12 so it will always stay after that.
Could you check master now?

**Comment by slodki** [comment]
It's sill wrong. Please wait - i'll fix it and rewrite git history for master branch.

**Comment by slodki** [comment]
fixed - please verity https://github.com/moneymanagerex/database/commit/b6cd48209aa76ae53a5ddeea71c0915458331299#diff-518de5b65d78e4a0ab2560f747c351e7

**Comment by gabriele-v** [comment]
> please verity b6cd482#diff-518de5b65d78e4a0ab2560f747c351e7

It's ok, than you


> Can someone turn on Travis CI for this repo?

I'm not administrator of this repo

**Pull request merged**
