### PR TITLE
Upgrade SPLITTRANSACTIONS_V1 with new fields, solve #4 and #7

### PR DESCRIPTION
**Pull request by gabriele-v**

### CODE REVIEW

**Comment by MisterY** [comment]
I assume tables_v1.sql will not be modified any longer once the upgrade code is implemented in desktop MMEX? The future migrations are all going to be in the sequential sql files (v5, v6 .. vn)?

**Comment by gabriele-v** [comment]
Yes, all migrations will be sequential but we still need to upgrade tables_v1.sql file because it's used in desktop version to auto-generate ORM files and create a new database, skipping all patches.

**Comment by MisterY** [comment]
Right, I see. 
On a second thought, I believe this is also how the Android create/upgrade mechanism works. I've already forgotten the details so need to have a second look. Cheers!

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team any concern about this PR ?

**Comment by guanlisheng** [comment]
personally i high recommend to add v2 and keep v1 as well

**Comment by vomikan** [comment]
If both V2 and v1 will be in DB and user start working on newest
mmex.... will  all new data stored in V2 or in both v1 and v2?
If user will daungrade to old mmex then lost new transactions.

2016-02-17 18:09 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by MisterY** [comment]
Related comment: https://github.com/moneymanagerex/database/issues/7#issuecomment-185784140
and an issuen in Android version: https://github.com/moneymanagerex/android-money-manager-ex/issues/692

**Pull request merged**
