### PR TITLE
preparing to v14

### PR DESCRIPTION
**Pull request by slodki**
#26 #32 #33
moneymanagerex/moneymanagerex#1621
moneymanagerex/moneymanagerex#1773
moneymanagerex/moneymanagerex#1775
moneymanagerex/moneymanagerex#1777
moneymanagerex/moneymanagerex#1782

### CODE REVIEW

**Comment by gabriele-v** [comment]
I cannot approve from mobile, but for me its ok.

**Comment by slodki** [comment]
moneymanagerex/android-money-manager-ex#1241
moneymanagerex/android-money-manager-ex#1141

**Comment by slodki** [comment]
What do you think @moneymanagerex/android-mmex-team @moneymanagerex/desktop-mmex-team about adding `NOT NULL` constraint to STATUS column and migrate all NULL to N or NN (for transfers)?

**Comment by gabriele-v** [comment]
It depend on how it's used N status in MMEX. 
Personally I think that it means "undefined" status, so null DB will be better, but it's just my 2C.
IAnyway considering that sume custom reports need to be changed for double char transfer, if we want to change it, better to change it now in this patch.

**Comment by slodki** [comment]
NULL is better for an undefined value of course but we have to store two concatenated statuses in one field for transfers...

NULL+letter == letter+NULL so we should:
* use N letter in place of NULL value
* or split STATUS field into 2 separate single-letter fields: STATUS and TOSTATUS and use NULL in place of N letter - this will require changes in Model_Checking.cpp sources AND reports

**Comment by gabriele-v** [comment]
Yep, you are right, so up to me it's fine to go with N

**Comment by MisterY** [comment]
In general, I prefer solutions that are backwards-compatible. 

The solution with reusing the existing field will be a breaking change. It will require a data migration for existing users as well as synchronized change in code across applications.

The option with the second field would be preferable in that sense, as well as from the perspective of data normalization.

**Comment by gabriele-v** [comment]
We will anyway need synchronized change on both desktop and application because allbtables are renamed removing _v1 suffix, regarding new field I don't think it's needed in this case (there will be a "status to" field used just for transfers?), doubt it's only about null or N value.

**Comment by lexa2** [comment]
Well, adding my two cents I'd say that it might be a good idea to tread transfers as two separate transactions. At least for some cases. It would better resemble what is actually happening in banking world.

It is typical (at least for Russia, not so sure about US/EU/UK/whatever) for bank transfer to take several days. For example when I send a transfer from my debit account in Raiffeisen to the another debit account in Sberbank typical sequence is money being withdrawn from the originating account at day N and then to arrive to target account at day N+3 (or even N+5 if N is just before the weekend). At the moment I have to track these transfers by creating two separate transactions - one withdrawal and one deposit - to have balance change dates properly reflected. Thus it might be good idea to introduce a new concept for "transfers": two separate but linked transactions for tracking these type of transfers. Having it this way also solves problem with STATUS field - no more two-letter values required. 

At the same time for some cases traditional "instantaneous" transfers are more appropriate. Examples are ATM interactions or cache transfers from one wallet to another. STATUS field for such transactions doesn't need to be two-letter due to transaction happening momentarily. For example, your account is withdrawn at the same moment as you receive money from the ATM so transaction status is always the same for both legs.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/1103

**Pull request merged**
