### PR TITLE
db v19: tags & color

### PR DESCRIPTION
**Pull request by n-stein**

### CODE REVIEW

**Comment by n-stein** [comment]
@vomikan @whalley Thoughts? Need any changes?

**Comment by vomikan** [comment]
> Thoughts? Need any changes?

We need to think about the future. It is possible to immediately add an is_active numeric (in fact binary) field for tags.
Color is not needed for tags?
You had an example like "diesel", and then only "gasoline" became relevant.

**Comment by n-stein** [comment]
> It is possible to immediately add an is_active numeric (in fact binary) field for tags.

The ACTIVE integer field is already there in TAG_V1.

> Color is not needed for tags?
> Group? Color for group?

I have no issue with adding additional fields. COLOR is simple enough. 

As for Group, what would the difference between a Group and a Tag be? For me, grouping tags seems a bit redundant since you can add an unlimited number of tags to a transaction. If you want to group items just create a new tag and tag everything in the group with it.  We could implement some type of hierarchy for tags, but I think this unnecessarily complicates what should be a relatively simple attribute. @tactilis any thoughts on that?

**Comment by nmsleal** [comment]
If you're planning to add color to the Tags, then the only way I see it won't break UI consistency would be to make them more graphical, similar to a plain/frozen button. They would need to change from text to text with background, font color and border. Border could be fixed to not over complicate. But this would require considerable effort, so I agree with @tactilis: let's hear the users feedback.

**Pull request merged**
